AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  justNotificationfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: justNotification.lambda_handler
      Runtime: python3.8
      CodeUri: justNotification
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: '{{resolve:ssm:execLambdaArn:1}}' 
      Environment:
        Variables:
          lineTokenMain: !Ref lineTokenMain      
          lineTokenPriv: !Ref lineTokenPriv      
Parameters:
  lineTokenMain:
    Type: String
  lineTokenPriv:
    Type: String
