AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  checkNRfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: checkNR.lambda_handler
      Runtime: python3.8
      CodeUri: checkNR
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: '{{resolve:ssm:execLambdaArn:1}}' 
