AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  checkGPSfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: checkGPS.lambda_handler
      Runtime: python3.8
      CodeUri: checkGPS
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: '{{resolve:ssm:execLambdaArn:1}}' 
      Environment:
        Variables:
          APPLE_ID: !Ref APPLEID
          PASSWORD: !Ref PASSWORD
          COOKIE_FILE: !Ref COOKIEFILE
          COOKIE_SESSION: !Ref COOKIESESSION
          PHONE_NAME: !Ref PHONENAME
Parameters:
  APPLEID:
    Type: String
  PASSWORD:
    Type: String
  COOKIEFILE:
    Type: String
  COOKIESESSION:
    Type: String
  PHONENAME:
    Type: String
